# Generated by Django 4.1.7 on 2023-02-21 11:40

from django.db import migrations

def create_data(apps, schema_editor):
    Image = apps.get_model('api_app', 'Image')
    Image(name="first image").save()


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
     migrations.RunPython(create_data),
    ]
