# Generated by Django 5.0.dev20230221075223 on 2023-02-22 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_date_created_image_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
        migrations.AlterField(
            model_name='image',
            name='bottom_left_coordinate',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='bottom_right_coordinate',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='top_left_coordinate',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='image',
            name='top_right_coordinate',
            field=models.CharField(max_length=60),
        ),
    ]
